apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-work-3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-work-3-app
  template:
    metadata:
      labels:
        app: home-work-3-app
    spec:
      restartPolicy: Always
      containers:
        - name: home-work-3-app
          image: ilmirsadykov/otus-home-work-2:home-work-3
          resources:
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-config
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-config
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-config
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-config
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pg-postgresql
