apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-work-3-ingress
  labels:
    name: home-work-3-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: home-work-3-service
            port: 
              number: 3000
