apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-work-3-service-monitor
  labels:
    app: home-work-3-app
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: home-work-3-app