apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-work-3-monitor
  labels:
    app: home-work-3-app
spec:
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  selector:
    matchLabels:
      app: home-work-3-app