---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: otus
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: otus
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      namespace: otus
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
          name: postgredb
        env:
          - name: POSTGRES_DB
            valueFrom: 
              secretKeyRef: 
                key: username
                name: database-creds
          - name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef:
                key: POSTGRES_USER
                name: postgres-config
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: password
                name: pg-postgresql
        volumeMounts:
        - name: data-pg-postgresql
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 4Gi
